In [11]:
import pandas as pd

In [12]:
df=pd.read_csv("financial_dataset.csv")

In [13]:
df

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00

In [14]:
df.head(5)

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1960 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    1960 non-null   int64
 1   Customer_ID       1960 non-null   object
 2   Customer_Name     1960 non-null   object
 3   Category          1960 non-null   object
 4   Sales             1960 non-null   float64
 5   Profit            1960 non-null   float64
 6   Quantity          1960 non-null   int64
 7   Payment_Status    1960 non-null   object
 8   City              1960 non-null   object
 9   Transaction_Date  1960 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(2), object(5)
memory usage: 168.4+ KB

In [30]:
df.tail()

<bound method NDFrame.tail of       Transaction_ID Customer_ID Customer_Name     Category    Sales  Profit  \
0              11317    CUST1134        Anjali    Furniture   1875.0  4126.0
1              11001    CUST1177         Sneha   Stationery  32521.0  9290.0
2              11069    CUST1478         Sneha         Food   8948.0  8683.0
3              11968    CUST1016         Priya    Furniture  20072.0  8320.0
4              10530    CUST1321         Priya   Stationery  32943.0  9336.0
...              ...         ...           ...          ...      ...     ...
1995           10700    CUST1427         Rahul  Electronics  14407.0  9016.0
1996           11500    CUST1136          Neha  Electronics   2105.0  5292.0
1997           11706    CUST1247         Vivek         Food  35927.0  2756.0
1998           10511    CUST1299         Rahul    Furniture  48447.0  1654.0
1999           11083    CUST1075          Arun     Clothing   8433.0  4718.0

      Quantity Payment_Status       City    Transaction_Date
0           16        Pending     Mumbai 2026-10-21 00:00:00
1           13           Paid  Bangalore 2026-05-16 00:00:00
2            3         Unpaid    Chennai 2026-06-19 00:00:00
3            1        Pending     Mumbai 2027-09-11 12:00:00
4            3           Paid  Bangalore 2025-09-22 12:00:00
...        ...            ...        ...                 ...
1995         8           Paid  Bangalore 2025-12-16 12:00:00
1996        13         Unpaid      Delhi 2027-01-20 12:00:00
1997         5        Pending  Mangalore 2027-05-03 12:00:00
1998         7         Unpaid      Delhi 2025-09-13 00:00:00
1999         5        Pending      Kochi 2026-06-26 00:00:00

[1960 rows x 10 columns]>

In [31]:
df.describe()

,Transaction_ID,Sales,Profit,Quantity,Transaction_Date
count,1960.000000,1960.000000,1960.000000,1960.000000,1960
mean,11001.544898,25265.580371,3474.547944,10.194898,2026-05-16 06:32:19.591836672
min,10001.000000,516.000000,-4982.000000,1.000000,2025-01-01 00:00:00
25%,10502.750000,13220.750000,-707.250000,5.000000,2025-09-08 21:00:00
50%,10999.500000,25147.046263,3469.098985,10.000000,2026-05-15 06:00:00
75%,11504.250000,37498.750000,7659.250000,15.000000,2027-01-22 15:00:00
max,12000.000000,49923.000000,11988.000000,19.000000,2027-09-27 12:00:00
std,578.744746,14261.616058,4884.706280,5.532933,NaN

In [15]:
df.isnull().sum()

Transaction_ID       0
Customer_ID          0
Customer_Name        0
Category            23
Sales               33
Profit              30
Quantity             0
Payment_Status       0
City                21
Transaction_Date     0
dtype: int64

In [16]:
df["Sales"]=df["Sales"].fillna(df["Sales"].mean())

In [17]:
df["Profit"]=df["Profit"].fillna(df["Profit"].mean())

In [18]:
df["Category"]=df["Category"].fillna(df["Category"].mode()[0])

In [21]:
df.isnull().sum()

Transaction_ID      0
Customer_ID         0
Customer_Name       0
Category            0
Sales               0
Profit              0
Quantity            0
Payment_Status      0
City                0
Transaction_Date    0
dtype: int64

In [19]:
df["City"]=df["City"].fillna(df["City"].mode()[0])

In [20]:
df.duplicated().sum()

np.int64(40)

In [22]:
df=df.drop_duplicates()

In [23]:
df["Category"]=df["Category"].str.strip().str.title()

C:\Users\ALRIYA SEQUEIRA\AppData\Local\Temp\ipykernel_10768\3960893055.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Category"]=df["Category"].str.strip().str.title()

In [24]:
df["Payment_Status"]=df["Payment_Status"].str.strip().str.title()

C:\Users\ALRIYA SEQUEIRA\AppData\Local\Temp\ipykernel_10768\1034170163.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Payment_Status"]=df["Payment_Status"].str.strip().str.title()

In [25]:
df["City"]=df["City"].str.strip().str.title()

C:\Users\ALRIYA SEQUEIRA\AppData\Local\Temp\ipykernel_10768\3137970100.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["City"]=df["City"].str.strip().str.title()

In [26]:
df["Transaction_Date"] = pd.to_datetime(df["Transaction_Date"], errors="coerce")
df.dtypes

C:\Users\ALRIYA SEQUEIRA\AppData\Local\Temp\ipykernel_10768\2971976620.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Transaction_Date"] = pd.to_datetime(df["Transaction_Date"], errors="coerce")

Transaction_ID               int64
Customer_ID                 object
Customer_Name               object
Category                    object
Sales                      float64
Profit                     float64
Quantity                     int64
Payment_Status              object
City                        object
Transaction_Date    datetime64[ns]
dtype: object

In [27]:
print("Cleaned Financial Dataset:")
df

Cleaned Financial Dataset:

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,Food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,Paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00

In [28]:
df.to_csv("cleaned_financial_transactions.csv")

In [32]:
df

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,Food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,Paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00